### ISSUE TITLE
.sb3 (Scratch 3) projects not supported

### ISSUE THREAD

**Issue by Luxiono** [djsrv/Snapin8r2#21]
What the title says - due to different conversions and file compression, Scratch 3.0 files can't be converted.

**Comment by Umbrestride** [comment]
Devastating! Ide LOVE to convert my project to python. its a huge commitment but maybe I can rewrite it in snap with some time.

**Comment by djsrv** [comment]
SB3 conversion is supported by Snapinator 3.0 https://snapinator.github.io/
